version: '3.6'

networks:
  dns-net:
    name: dns_net
    ipam:
      config:
        - subnet: 172.24.10.0/24

volumes:
  alfis_data:
    name: alfis_data
  emc_data:
    name: emc_data

services:
  unbound:
    image: blockchain-unbound
    build:
      context: ./unbound
    container_name: blockchain-unbound
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - dns-net

  emc:
    image: wg00/emercoin:0.8.3
    container_name: emer-dns
    volumes:
      - emc_data:/emc
      - /etc/localtime:/etc/localtime:ro
    networks:
      dns-net:
        ipv4_address: 172.24.10.10
    restart: unless-stopped
    stop_grace_period: 30s

  alfis:
    image: cofob/alfis
    container_name: alfis
    volumes:
      - alfis_data:/storage
    restart: unless-stopped
    stop_grace_period: 10s
    networks:
      dns-net:
        ipv4_address: 172.24.10.20

   

